### ISSUE TITLE
Want a build badge?

### ISSUE THREAD

**Issue by mkinney** [monerium/smart-contracts#22]
I was experimenting with adding a build badge to the README.md. I broke out the compile, migrate, test, and coverage to different build steps. Not sure if that is what makes sense. I didn't get the slither nor smartcheck steps to work.

Check out https://github.com/mkinney/smart-contracts/tree/badges to see what it would look like and if you click on the build badge, it takes you to travis-ci.

If you want, I could create a PR for this. Note that we would probably want to change my travis-ci account to a monerium account and change the branch to master or development or have badges for each. (up to you) Setting up a travis-ci account is free for open source projects.

If you don't want a build badge, feel free to just close this issue.

**Comment by arnigudj** [comment]
thanks @mkinney, this is greatly appreciated! We are designing the build pipeline as we speak, so this is will be a great reference.

**Comment by mkinney** [comment]
Ok. Let me know if you want the PR or need any help getting setup on travis-ci. (or wherever you want to do your ci pipeline)

**Comment by arnigudj** [comment]
thanks @mkinney ! I've added the travis-ci badge and build.

**Comment by mkinney** [comment]
That's really cool!
